version: "3.6"
services:
#  frontend:
#    image: austinv11/discord4j:web-frontend
##    build: web-frontend
#    volumes:
#      - type: volume
#        source: frontend-data
#        target: /dist/
#        read_only: false
#        volume:
#          nocopy: false
##    restart: always Spams the logs if we do this
  frontend:
    image: austinv11/discord4j:web-old
#    build: web-frontend
    volumes:
      - type: volume
        source: frontend-data
        target: /dist/
        read_only: false
        volume:
          nocopy: false
#    restart: always Spams the logs if we do this

  nginx:
    depends_on:
      - frontend
    image: austinv11/discord4j:nginx #-nossl # nossl for testing
#    build: nginx
    volumes:
      - type: volume
        source: frontend-data
        target: /var/www/html/
        read_only: true
        volume:
          nocopy: false
      - ../nginx_data/:/cert
    restart: always
    ports:
      - 80:80
      - 443:443
#      - 1234:1234
#      - 2345:2345
#      - 3456:3456
#      - 4567:4567
#      - 5678:5678
#      - 9000:9000
#      - 2314:2314
    networks:
     nginx-net:

  database:
    image: postgres:10.4-alpine
    #build: database
    restart: always
    ports:
      - 5432:5432
    # Don't forget to set these environment variables!
    environment:
#      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../postgres_data/:/var/lib/postgresql/data/pgdata
    networks:
     db-net:
#
#  confluence:
#    depends_on:
#      - database
#    image: austinv11/discord4j:confluence
#    #build confluence
#    restart: always
#    ports:
#      - 3456:8090
#      - 3457:8091
#    volumes:
#      - ../confluence_data/confluence:/var/atlassian/confluence
#      - ../confluence_data/conf:/opt/atlassian/confluence/conf
#    networks:
#     nginx-net:
#     db-net:
#
#  jira:
#    depends_on:
#      - database
#    image: austinv11/discord4j:jira
#    #build jira
#    restart: always
#    ports:
#      - 2345:8080
#    volumes:
#      - ../jira_data/jira/:/var/atlassian/jira
#      - ../jira_data/conf:/opt/atlassian/jira/conf
#    networks:
#     nginx-net:
#     db-net:

  ci:
    depends_on:
      - database
    image: drone/drone:0.8.5
    restart: always
    ports:
      - 1234:8000
      - 9000
    volumes:
      - ../drone_data/:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=https://ci.discord4j.com
      - DRONE_GITHUB=true
      - DRONE_ORGS=Discord4J
      - DRONE_ADMIN=austinv11
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT} # Stuff from manually created gh OAuth app
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET} # Arbitrary secret for internal communication
#      - DRONE_DATABASE_DRIVE=postgres  TODO: use postgres later
#      - DRONE_DATABASE_DATASOURCE=postgres://postgres@database:5432/postgres?sslmode=disable
    networks:
     nginx-net:
     drone-net:
     db-net:

# 2 drone agents capable of running 4 parallel builds, each

  drone-agent1:
    image: drone/agent:0.8.5
    command: agent
    restart: always
    depends_on:
      - ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ci:9000
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_MAX_PROCS=4
    networks:
      drone-net:

  drone-agent2:
    image: drone/agent:0.8.5
    command: agent
    restart: always
    depends_on:
      - ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ci:9000
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_MAX_PROCS=4
    networks:
      drone-net:

  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../portainer_data/:/data
    networks:
     nginx-net:

  webhook:
    depends_on:
      - nginx
    image: austinv11/discord4j:webhook
    restart: always
    ports:
      - 2314:2314

volumes:
  frontend-data:
networks:
  nginx-net:
  db-net:
  drone-net: