version: "3.6"
services:
  frontend:
    image: austinv11/discord4j:web-frontend
#    build: web-frontend
    volumes:
      - type: volume
        source: frontend-data
        target: /dist/
        read_only: false
        volume:
          nocopy: false
#    restart: always Spams the logs if we do this

  nginx:
    depends_on:
      - frontend
    image: austinv11/discord4j:nginx-nossl # nossl for testing
#    build: nginx
    volumes:
      - type: volume
        source: frontend-data
        target: /var/www/html/
        read_only: true
        volume:
          nocopy: false
    restart: always
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 1234:1234
      - 2345:2345
      - 3456:3456
      - 4567:4567
      - 5678:5678

  database:
    image: austinv11/discord4j:database
    #build: database
    restart: always
#    ports:
#      - 5432:5432
    # Don't forget to set these environment variables!
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data"

  confluence:
    depends_on:
      - database
      - nginx
    image: austinv11/discord4j:confluence
    #build confluence
    restart: always
    ports:
      - 8090:3456
      - 8091:3457

volumes:
  frontend-data:
