# https://docs.requarks.io/wiki/install/installation/configuration-file

title: Discord4J Official Wiki

host: https://wiki.discord4j.com
port: 5678

paths:
  repo: ./discord4j-wiki-clone
  data: ./temp-data

lang: en

public: true
defaultReadAccess: false

auth:
  local:
    enabled: true
  google:
    enabled: true
    clientId: $(GOOGLE_CLIENT_ID)
    clientSecret: $(GOOGLE_CLIENT_SECRET)
  microsoft:
    enabled: true
    clientId: $(MICROSOFT_CLIENT_ID)
    clientSecret: $(MICROSOFT_CLIENT_SECRET)
  github:
    enabled: true
    clientId: $(GITHUB_CLIENT_ID)
    clientSecret: $(GITHUB_CLIENT_SECRET)

# A randomly generated string, used when encrypting sessions.
# 256-bit keys are usually a good choice.
# You can use this key generator (http://randomkeygen.com/) to generate one.
sessionSecret: $(SESSION_SECRET)

# mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
db: mongodb://wikidb:27017/wiki

git:
  url: https://github.com/Discord4J/discord4j-wiki.git
  branch: master
  auth:
    type: basic
    username: $(GIT_USER_NAME)
    password: $(GIT_PASSWORD)
  serverEmail: $(GIT_EMAIL)
  showUserEmail: true

features:
  mathjax: false # Cool, but not needed
